### ISSUE TITLE
Can we get dates to show up on blog posts?

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-docs#100]

**Comment by MattDodsonEnglish** [comment]
It's kind of hacky but I added what I think is a viable fix with 70f4994436f3f7145977998cfe14d68314599510.

I've added publish and edit date below the H1. Other reasonable places would be:
- before the H1
- after the lead
- at the end of the article

To see what the end of the article would look like, scroll down to the end of the data-model pages.  To move the date position, go to `layouts/blog/single.html` and just move the entire "Date" div to wherever you want it to go.
