### ISSUE TITLE
More organization to Chifra READMEs and their single page reference

### ISSUE THREAD

**Issue by MattDodsonEnglish** [TrueBlocks/trueblocks-docs#116]
Although I think it's good that the READMEs for the tools now show the `chifra` command, I still think the docs should reference somewhere what underlying tool in `./src/tools` that `chifra <cmd>`calls.

I also think having "Powered by TrueBlocks&trade;" at the bottom of each page might be a bit over-enthusiastic branding. This is definitely true on the single page reference, aka super-README, where it's repeated many times over.

For the super-readme, aka the single page website reference, I think it'd be better to organize the tools in some hierarchy of function, rather than by alphabetical order. I think the organization of `chifra --help` is a great start. On my side, I could work on this by using an asciidoc file with a few `include:` commands to template it out. An alternative would be to have a makefile that generates the single page reference somewhere directly in the `core`repository. I'm not sure what's better yet. Maybe there's a more sensible third option too.

**Comment by tjayrush** [comment]
Closing.
