### ISSUE TITLE
A couple of images from earlier

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-docs#12]
<img width="1429" alt="AAAAA - Ethereum Data Structures" src="https://user-images.githubusercontent.com/5417918/114959478-266b0280-9e33-11eb-8174-005e9e378322.png">

**Comment by MattDodsonEnglish** [comment]
I've added the relations table to /data-models with commit 34ad674fb16142147b3026e0254ea1015acbb5ac

I think it could be improved, both in terms of information density and aesthetics, but it's a good start.

> https://github.com/TrueBlocks/trueblocks-docs/issues/12#issuecomment-820846387
I love this second table, with the "what can I do? How can I do it?" sequence.
But it looks outdated. If we had a new version, it'd be perfect for the command line section.

The last three pics are interesting, but I think they are more about the business model.

Closing this, but we can always revisit the images.
