### ISSUE TITLE
Upload the shell script to build the mega-readme

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-docs#18]
If you think it makes sense, please upload the shell script that builds the mega-readme when it's ready. It would help me see that my changes to the underlying README files does not break anything before pushing changes to `core`.

**Comment by MattDodsonEnglish** [comment]
Added with this commit:

1e9a05e2fb806b0fd7cacf3184b870422467cf34

**Comment by tjayrush** [comment]
LGTM
