### ISSUE TITLE
Ordering of groups in mega-readme should be the same as chifra command

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-docs#19]
When I type `chifra`, I get this ordering of the groups of commands:

```
Accounts
Data
State
Admin
Other
```

When I look at the help file, I see this ordering:

```
Accounts
Data
Admin
Other
State
```

I'd like them to agree and use `chifra's` ordering.

**Comment by MattDodsonEnglish** [comment]
Fixed with this commit:
ec848ee91d42b6c2c0e5e17e1408610f65c74dcc
