### ISSUE TITLE
Change 'Data' group to 'Blockchain Data'

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-docs#20]

**Comment by MattDodsonEnglish** [comment]
With commit, ec848ee91d42b6c2c0e5e17e1408610f65c74dcc, I changed this on the doc side.

**Comment by tjayrush** [comment]
How would you feel about using the words "Chain Data" instead of "Blockchain Data"? I think everyone would understand what that means, plus it's shorter.

I was also thinking we could do "Chain State" instead of just "State" as that would explain things more clearly.

I am going to make that change on the 'core' side (you can see it with `chifra --help`).

Let's discuss.

**Comment by tjayrush** [comment]
New core code uses 'Chain Data' and 'Chain State'. I like it, let's settle on it.
