### ISSUE TITLE
Omission of withdrawal appearances in spec

### ISSUE THREAD

**Issue by perama-v** [TrueBlocks/trueblocks-docs#203]
## Description
Note is made that in v0.51.0 of the UnchainedIndex, the definition of a valid location for an appearance does not include the "withdrawals" field of the execution block. 

Specifically, the "address" field in each withdrawals object in the array. E.g., In block `17190873`, the following snippet shows that for address `0x1cedc0f3af8f9841b0a1f5c1a4ddc6e1a1629074` the balance increases (at least) twice (by `0xbeb4a8` and `0xbecf2b`). 
```json
...
  "withdrawalsRoot": "0x78706ed8664fdab1114d686203e86ef5c9d7c6a8a70c1f2ee3efe44a1cfeeff8",
  "withdrawals": [
    {
      "index": "0x2615b2",
      "validatorIndex": "0x4a929",
      "address": "0x1cedc0f3af8f9841b0a1f5c1a4ddc6e1a1629074",
      "amount": "0xbeb4a8"
    },
    {
      "index": "0x2615b3",
      "validatorIndex": "0x4a92a",
      "address": "0x1cedc0f3af8f9841b0a1f5c1a4ddc6e1a1629074",
      "amount": "0xbecf2b"
    },
    ...
}
```
As such changes constitute important accounting information for an address, it seems that they should be part of the spec
(and index).

**Comment by tjayrush** [comment]
Note that this has now been fixed in a branch, but it's not quite ready for prime time. Coming soon to the `master` branch. Needs documentation still.

**Comment by tjayrush** [comment]
> `v2.43`, it is enabled by the standard eth namespace `--http.api=eth,...`
> 
> * `"params": ["0x1064FD9", false]` returns header
> * `"params": ["0x1064FD9", true]` returns header, transactions, withdrawals
> 
> Edit: with `false` param the withdrawals are also included

I think this is now incorrect. `eth_getBlockByNumber` now returns withdrawals with either `true` or `false`. Just documenting that.

**Comment by tjayrush** [comment]
I'm going to close this. `chifra blocks` and `chifra export` now both have a `--withdrawals` option. And, also, `chifra scrape` now indexes Withdrawals. We've not yet added withdrawals to the `--accounting` or `--statement` options but those features a now limited as we clean up some other issues with caching and concurrency. (There's other things that need to be fixed with `--accounting`, and we think not so many people use it currently.

**Comment by tjayrush** [comment]
The above refers to the `develop` branch. We'll be merging with `master` in two wooks.

**Comment by tjayrush** [comment]
Withdrawals are identified in `develop` with `txid=99995`.
