### ISSUE TITLE
Can we use non-breaking or nowrap so --options don't break in the options tables.

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-docs#21]

**Comment by MattDodsonEnglish** [comment]
Besides the wrap, which I agree is bad, there is another issue. The processor uses a ligature, converting -- into an em dash, which is just straight up wrong.

Fixing the table width could be difficult. I think the first solution to try is what you proposed: use HTML encoding. Use the hyphen symbol `&#8208; ` and non breaking spaces.


So `-- verbose` Would be `&#8208;&#8208;&nbsp;verbose`

**Comment by MattDodsonEnglish** [comment]
Jay has fixed this by using a shortcode in the tables.

https://github.com/TrueBlocks/trueblocks-docs/commit/2d7bfc17e967105d2209abc7d5e9b702e2acb003
