### ISSUE TITLE
Re-order blog organization based on Tags

### ISSUE THREAD

**Issue by MattDodsonEnglish** [TrueBlocks/trueblocks-docs#34]
While I think it's a great idea to organize the longform content, my first experiments make me think that the docs structure is not ideal for the blog. Chiefly, rather than a directory/hierarchy structure, I think it'd be better to reorganize the blog based on tags.
This is for a few reasons:

* Working through the docs is fairly procedural, so it makes sense to organize by hierarchies. However the blog is freeform,  roaming from topic to topic.
* There's no clear distinction between topics, e.g. a post could be a "recipe", "explainer", "trueblocks article" and "ethereum" article all at the same time. Tags accomodate multiple groupings
* Tags offer an ordering flexibility, letting us sort by both tags and by date.
* Now the blog and the docs appear exactly the same, causing, I believe, some UX confusion and cognitive discomfort for the reader

I propose having a single long list of blog posts on `/blogs` with a tag cloud on the side, something like this: https://themes.gohugo.io/tags/simple/

Then, maybe each tag grouping can have its own separate listed page.

Now the task is for me to learn enough about Hugo to make this work.

**Comment by MattDodsonEnglish** [comment]
> Then, maybe each tag grouping can have its own separate listed page.

I think something like this is doable

![image](https://user-images.githubusercontent.com/47385188/121214970-fa2d9a00-c855-11eb-8495-4773321abcfd.png)
![image](https://user-images.githubusercontent.com/47385188/121215519-77590f00-c856-11eb-8d04-27ca25a032fb.png)
![image](https://user-images.githubusercontent.com/47385188/121216326-2d245d80-c857-11eb-8547-f73021a17490.png)

Again, 
> Now the task is for me to learn enough about Hugo to make this work.

**Comment by tjayrush** [comment]
I think this makes sense. Other blog platforms I've used use tags, so maybe that's better. Go for it.

**Comment by MattDodsonEnglish** [comment]
There are still some blog issues, as shown here: https://github.com/TrueBlocks/trueblocks-docs/issues/35

But this specific issue is resolved.
