### ISSUE TITLE
Starting fresh from README, go through install process

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-docs#55]
Starting on a fresh machine (reasonably fresh), follow the instructions in the README.md in the `jay-explorer` branch at the root of this repo to get both the old version (in the `master` branch) and the new version (in branch `jay-explorer` running. This includes downloading and installing the TrueBlocks core (the back end).

I do not expect this process will go smoothly, so the main tasks here are:

1. Document the stumbling points with the installation
2. Identify confusing / incorrect instructions
3. Help smooth out the path for new users

The only real goal for this task is to have running versions of both the old explorer and the new explorer including a working, local back end.

**Comment by MattDodsonEnglish** [comment]
I think various docs now cover the points that this issue addresses.
