### ISSUE TITLE
Hugo build not working on some machines

### ISSUE THREAD

**Issue by MattDodsonEnglish** [TrueBlocks/trueblocks-docs#72]
In this pull request, Dawid reported getting this error. 

`Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: _default/single.html:3:5: executing "_default/single.html" at <partial "head/head.html" .>: error calling partial: execute of template failed: template: partials/head/head.html:6:36: executing "head/stylesheet" at <partial "head/stylesheet.html" .>: error calling partial: "/Users/dawid/Upwork/trueblocks-docs/layouts/partials/head/stylesheet.html:7:45": execute of template failed: template: partials/head/stylesheet.html:7:45: executing "partials/head/stylesheet.html" at <toCSS $options>: error calling toCSS: no Resource provided in transformation

The build was still working on my machine and Jay's, so I didn't worry about it. However, trying on a different ubuntu machine, the build fails with the same error:

Not sure what this is about. This is the offending line in `partials/head/stylesheet.html` . I have done some Googling, and found similar errors on Hugo forums, but nothing that matched too closely. I didn't look deeply.

```
  {{ $css := resources.Get "scss/app.scss" | toCSS $options | postCSS (dict "config" "config/postcss.config.js") -}}
```

  Going to try a few different things.

* Add latest upstream changes to configuration (must be careful not to add too much, or break custom list pages)*
* Remove the offending line and see what happens. 
* Ask for help in the doks discussion channel, 
* Sink teeth into hugo pipes and scss

**Comment by MattDodsonEnglish** [comment]
On a fresh repo on my machine, I was able to reproduce. Makes it easier to debug.

I think this is something about JS package files, or the assetts/scss directory. Hopefully not as big a headache as I thought.

**Comment by MattDodsonEnglish** [comment]
Back to working on my machine, not on the other Ubunut machine I'm using. At least the message changed:

 hugo v0.88.1-5BC54738+extended linux/amd64 BuildDate=2021-09-04T09:39:19Z VendorInfo=gohugoio
ERROR 2021/09/15 00:15:30 render of "page" failed: execute of template failed: template: blog/single.html:28:7: executing "blog/single.html" at <partial "footer/script-footer.html" .>: error calling partial: "/home/runner/work/docs-testing/docs-testing/layouts/partials/footer/script-footer.html:39:23": execute of template failed: template: partials/footer/script-footer.html:39:23: executing "partials/footer/script-footer.html" at <append $flexSearch>: error calling append: reflect: call of reflect.Value.Type on zero Value
ERROR 2021/09/15 00:15:30 render of "page" failed: execute of template failed: template: blog/single.html:28:7: executing "blog/single.html" at <partial "footer/script-footer.html" .>: error calling partial: "/home/runner/work/docs-testing/docs-testing/layouts/partials/footer/script-footer.html:39:23": execute of template failed: template: partials/footer/script-footer.html:39:23: executing "partials/footer/script-footer.html" at <append $flexSearch>: error calling append: reflect: call of reflect.Value.Type on zero Value
ERROR 2021/09/15 00:15:30 render of "page" failed: execute of template failed: template: blog/single.html:28:7: executing "blog/single.html" at <partial "footer/script-footer.html" .>: error calling partial: "/home/runner/work/docs-testing/docs-testing/layouts/partials/footer/script-footer.html:39:23": execute of template failed: template: partials/footer/script-footer.html:39:23: executing "partials/footer/script-footer.html" at <append $flexSearch>: error calling append: reflect: call of reflect.Value.Type on zero Value
ERROR 2021/09/15 00:15:30 render of "page" failed: execute of template failed: template: blog/single.html:28:7: executing "blog/single.html" at <partial "footer/script-footer.html" .>: error calling partial: "/home/runner/work/docs-testing/docs-testing/layouts/partials/footer/script-footer.html:39:23": execute of template failed: template: partials/footer/script-footer.html:39:23: executing "partials/footer/script-footer.html" at <append $flexSearch>: error calling append: reflect: call of reflect.Value.Type on zero Value
ERROR 2021/09/15 00:15:30 failed to render pages: render of "page" failed: execute of template failed: template: _default/single.html:28:7: executing "_default/single.html" at <partial "footer/script-footer.html" .>: error calling partial: "/home/runner/work/docs-testing/docs-testing/layouts/partials/footer/script-footer.html:39:23": execute of template failed: template: partials/footer/script-footer.html:39:23: executing "partials/footer/script-footer.html" at <append $flexSearch>: error calling append: reflect: call of reflect.Value.Type on zero Value
Error: Error building site: TOCSS: failed to transform "scss/app.scss" (text/x-scss): SCSS processing failed: file "stdin", line 2, col 1: File to import not found or unreadable: bootstrap/scss/functions. 
Total in 298 ms

**Comment by MattDodsonEnglish** [comment]
It was so simple: this hugo theme has some customizations that use npm. Developers need to run `npm install` to get the dependencies before the site will build with `hugo server`.

@dszlachta  If you need to build the site again, trying running `npm install` first :-).

Also updated the README:
https://github.com/TrueBlocks/trueblocks-docs/commit/9cb19afc5e437bb62f77ff479bd14a93c7e1adb9

**Comment by dszlachta** [comment]
I will, thank you :)

Dawid Szlachta
