### ISSUE TITLE
Update docs site for upstream

### ISSUE THREAD

**Issue by MattDodsonEnglish** [TrueBlocks/trueblocks-docs#74]
Over the last months, the doks upstream has made some nice changes:
https://getdoks.org/

I think the TrueBlocks site would be improved with dropdown category menus (cleaner) and especially, using the new search, which seems much better than the one we use.

However, it's not as easy as just copying, because all the pages (except for `/docs`) have formatting customization. This is especially true for the blog list page, and the blog tag sidebars. I described these customizations here:

https://github.com/TrueBlocks/trueblocks-docs/issues/35#issuecomment-916885150

**Comment by MattDodsonEnglish** [comment]
I made some attempts to update with commit  edca0683c566f7bd07708f99445f910d3e8424c7.

However, it introduced multiple problems:
- On the sidebar, the dropdown menu only works with JS enabled. I think major content and docs features should be accessible with pure HTML/CSS.
- Darkmode has multiple issues:
   * It only toggles after reloading the page
   * On the dark version of the recipes posts, the syntax highlighting is unreadable (see screenshot)

I think syntax problem is related to new highlighter package being used, `hljs`. I believe the old version didn't use that. I'm rolling this commit back. 

````html
<pre><button class="btn btn-copy"></button><code class="language-[toml] hljs ini"><span class="hljs-section">[settings]</span>
<span class="hljs-attr">rpcProvider</span> = <span class="hljs-string">"http://localhost:8545"</span>
<span class="hljs-attr">cachePath</span> = <span class="hljs-string">"~/.quickBlocks/cache"</span>
</code></pre>
```

![/recipes, 2021-10-21. The code fences are white with a white background](https://user-images.githubusercontent.com/47385188/135614158-249b4553-3c13-4b74-968a-8708da0bf38e.png)

**Comment by tjayrush** [comment]
Hi @MattDodsonEnglish Maybe you can close this issue?

**Comment by MattDodsonEnglish** [comment]
Yes I think so, but "fix search" is definitely an issue that should be solved. I just don't know how :-(

**Comment by tjayrush** [comment]
Armin: This one appears to be closed, is there a reason you linked to it? Because it's related to search?
