### ISSUE TITLE
short options on chifra help files break after dash

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-docs#75]
Is there some way to force markdown to not break after the dash in the short options on, for example, this page https://trueblocks.io/docs/chifra/chainstate?

Open this in Chrome and notice that the `-d` option (and others) appears like this:

![image](https://user-images.githubusercontent.com/5417918/133705811-759b7814-df74-41c8-b889-2c08f39a81a1.png)

It looks really bad.

I simple fix might be to make the width of the inner table a bit wider.

**Comment by MattDodsonEnglish** [comment]
Very related to https://github.com/TrueBlocks/trueblocks-docs/issues/21, which I closed as this issue is better described.

A possible hack would be to use non breaking spaces in the column headers. This should expand the table width. I will try tomorrow.

**Comment by MattDodsonEnglish** [comment]
And in my opinion the ligature is even worse, because it is straight up syntactically wrong. Hopefully a little HTML character entities.

**Comment by tjayrush** [comment]
I think I can figure this out. I found a solution that works with short codes. I can insert the short code into the generated code just above the table. It works well. I should be able to post this later tonight.

I know nothing about the ligatures.

**Comment by MattDodsonEnglish** [comment]
> I know nothing about the ligatures.

From the other issue, I proposed a solution that should work:

Besides the wrap, which I agree is bad, there is another issue. The processor uses a ligature, converting -- into an em dash, which is just straight up wrong. So one change might be to use html encoding for hyphens.

**Comment by tjayrush** [comment]
I am pushing a change to master right now that will fix (and I will close) this issue. I can easily generate the html encoding for the dashes. I will open (and then close) an issue for that as shortly. Closing this one with the latest push.
