### ISSUE TITLE
Ligatures

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-docs#76]
I tried to replace the dashes in the chifra command line docs with `&#45;`. It didn't seem to work.

We could, I suppose, simply remove the dashes and double dashes from the doc, but that's a bit extreme.

**Comment by MattDodsonEnglish** [comment]
Interesting, can you try `&#8208;` ? I just was able to use that on my local machine.

Another alternative is to use `monospace` font for flags. See screenshot for examples of each one
![different ways of avoiding -- ligatures](https://user-images.githubusercontent.com/47385188/133777316-9608a45c-1eef-4daa-8caf-59b2c5075cfa.png)

**Comment by tjayrush** [comment]
Do you have a preference? I like the backticks. Let me try that.

**Comment by tjayrush** [comment]
Please close this if you agree that the issue is fixed with the PR.

**Comment by MattDodsonEnglish** [comment]
LGTM
