### ISSUE TITLE
Clean up blog

### ISSUE THREAD

**Issue by MattDodsonEnglish** [TrueBlocks/trueblocks-docs#89]
Jay writes
> One day, I do want to go through the blog posts and clean them up. I feel like, when I copied them over, I got a lot of weird formatting including broken links, missing images, bad formatting. You don't have to worry about any of that, but please make an issue.
https://discord.com/channels/570963863428661248/650170625155006484/897839178522431498

~In addition to the formatting issues, the blog also a number of deadlinks. I want to add an automatic link checker for the site. However, I'm not going to run the link checker on the blog, for a few reasons:~

~* Some of the blog post have dead links because of link rot: old DAO forum posts, ect. I tried to dig in and fix some, but sometimes removing the link makes the sentence look strange, causing me to make other edits.~
~* Other times I think I could find some related link but I don't think it's worth the trouble to track down.~
~* Some links I just don't have context to assess~

**Comment by tjayrush** [comment]
Armin: This is a much larger task. Let's hold off on this one until we complete the others. There's other work than just fixing links including copying some stuff from Medium.

Put this one on hold.
