### ISSUE TITLE
Fix search

### ISSUE THREAD

**Issue by MattDodsonEnglish** [TrueBlocks/trueblocks-docs#90]
As we have a pretty good amount of content now, a good search becomes more important. There's a UX paradigm that all users are on some spectrum of searchers and clickers. As younger generations become more and more accustomed to using search for retrieval (https://www.theverge.com/22684730/students-file-folder-directory-structure-education-gen-z), searchers probably occupy an increasingly large portion of documentation readers.

Our search is not good. It has a strange, truncated bar, and it doesn't return some results. The only content it searches over is docs.

At least, it'd be good to search over Docs, Data-model, and blog if possible.

On the other hand, the mainstream doks search is pretty good (thought it doesn't cover the blog). They call a third-party algolia API, but I believe it'd be possible to improve without using 3rd parties.

The real tricky part is extracting the search parts of the Doks codebase without breaking anything else. If that doesn't work, I might need to research how flexSearch works a little bit too: https://github.com/nextapps-de/flexsearch .

**Comment by tjayrush** [comment]
I don't mind at all using a third party here if it's easy and cheap.

**Comment by tjayrush** [comment]
That looks amazing...keep it up.

**Comment by tjayrush** [comment]
So this is an update for Armin. I'll add separate comments so we can track the threads.

>  It has a strange, truncated bar, and it doesn't return some results

This is the first thing to fix. (1) that the search bar is weird and shortened, and (2) that it doesn't really search the content very well. (Although, I'm not sure we want to expand the search all the way into the Blog as this might pollute the results.)

**Comment by tjayrush** [comment]
The original poster mentions using a third party, but I think that discussion was a bit misguided. He later mentions that we could possibly get search metrics which would be available from a third-party solution and onerously difficult to produce on our own. My desire would be a search solution that produces good results, stays on our server (at least in the way it looks), and allows me to see what people are searching for.

If there are options for third party search, I'd appreciate you present them to me before implementing them, as I'd like to spend some time reading/thinking before we implement.
