### ISSUE TITLE
/blog list and /tag/<category> lists are slightly misaligned

### ISSUE THREAD

**Issue by MattDodsonEnglish** [TrueBlocks/trueblocks-docs#92]
Discovered by Jay:
![Screenshot posted on 2021-10-18](https://user-images.githubusercontent.com/47385188/139113386-f3747cb7-3202-41cb-8e5f-f5e22a68e601.png)

----
I have no idea why. I thought it'd be fixed by making the tag/<category> page tri-columnar. However, now the two list pages are almost identical. I tried capitalizing the h1 heading, and removing quotes, no fix. I even tried to making the H1 heading "Blog", so the page should be identical. Still misaligned.
https://github.com/TrueBlocks/trueblocks-docs/blob/master/layouts/tags/list.html
https://github.com/TrueBlocks/trueblocks-docs/blob/master/layouts/blog/list.html

I suppose we would need to inspect the page source to figure out what's going on there.

**Comment by tjayrush** [comment]
Armin: This is just a formatting issue. It may already be corrected, so if you can't see it, please just close this issue.
