### ISSUE TITLE
Parameter "fmt" is not listed in the API docs

### ISSUE THREAD

**Issue by dszlachta** [TrueBlocks/trueblocks-docs#94]
Our API supports switching format between JSON, API (JSON, but with metadata added in `meta` field), CSV and tab separated values. However, API docs don't mention `?fmt=` parameter. 

`fmt` is also missing from `openapi.yaml`, making autogenerated SDKs incomplete

**Comment by tjayrush** [comment]
By the way. Now that you're looking at this from the front end perspective, think from a front end user's point of view. If the API doesn't provide something that it should, make a note of that. With the auto-gen code, it's now very easy to add new endpoints and options.

**Comment by dszlachta** [comment]
Yes, I will be fixing these.
Sure thing, will do 👍

**Comment by tjayrush** [comment]
As of Oct 24, 2022, the `--fmt` option (and other globally available options) do not appear in the API docs.

**Comment by tjayrush** [comment]
Stale
