### ISSUE TITLE
cache_traces is missing from `export` endpoint specification

### ISSUE THREAD

**Issue by dszlachta** [TrueBlocks/trueblocks-docs#95]
The current `openapi.yaml` file doesn't list `cache_traces` as a possible parameter of `export` endpoint.

We use this parameter in the UI, but it is missing in the SDK

**Comment by tjayrush** [comment]
This has been added to the fix/camelCaseApi branch. Once that branch is merged, this can be closed.

**Comment by tjayrush** [comment]
No, it's not missing.
